include: package:flutter_lints/flutter.yaml

linter:
  rules:
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "lib/src/constants/locale_keys.dart"
    - "android/**"
