name: watchable
description: "A new Flutter project."
publish_to: 'none'
version: 0.4.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  shimmer: ^3.0.0
  sentry_flutter: ^8.3.0
  in_app_update: ^4.2.3
  store_checker: ^1.4.0

  supabase_flutter: ^2.5.6
  supabase_auth_ui: ^0.5.0
  google_sign_in: ^6.2.1

  tmdb_api:
  youtube_player_flutter: ^9.0.1
  onesignal_flutter: ^5.2.1

  # dart run easy_localization:generate -f keys -o locale_keys.dart -O lib/src/constants -S assets/translation
  easy_localization: ^3.0.7
  flex_color_scheme: ^7.3.1
  flutter_spinkit: ^5.2.1
  badges: ^3.1.2
  fancy_shimmer_image: ^2.0.3
  cached_network_image: ^3.3.1
  infinite_scroll_pagination: ^4.0.0
  styled_text: ^8.1.0
  el_tooltip: ^2.0.0
  grouped_list: ^6.0.0

  intl: ^0.19.0
  collection: ^1.18.0
  path: ^1.9.0
  go_router: ^14.2.0

  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  freezed_annotation:
  json_annotation:

  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  loading_icon_button: ^0.0.6
  toastification: ^2.0.0
  wolt_modal_sheet: ^0.6.1
  tuple: ^2.0.2
  image_picker_widget: ^2.4.1
  flutter_gravatar: ^2.0.2
  avatar_stack: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  riverpod_generator:
  riverpod_lint:
  freezed:
  json_serializable:

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/translation/