name: watchable
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.3.4
  supabase_auth_ui: ^0.4.3

  # dart run easy_localization:generate -f keys -o locale_keys.dart -O lib/src/constants -S assets/translation
  easy_localization: ^3.0.5
  flex_color_scheme: ^7.3.1
  flutter_spinkit: ^5.2.0
  badges: ^3.1.2

  intl: ^0.19.0
  go_router: ^13.2.1

  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  freezed_annotation:
  json_annotation:

  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  loading_icon_button: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner:
  riverpod_generator:
  riverpod_lint:
  freezed:
  json_serializable:

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/translation/
